#any playbook in ansible start with ---
- #task you are defining in playbook
  hosts: git-vm

  tasks: #python dictionary 
    - name: update my ubuntu sytem 
      apt:
        update_cache: yes
    - name: install required package
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release 
    - name: add gpg key
      apt_key:
        url: "https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg"
        state: present 
    - name: add ansible repo into source list
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present 
        filename: docker 
